DALELk/Controllers/CategorysController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using DALELk.Data;
using DALELk.Models;
using DALELk.Repository;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace DALELk.Controllers
{
    public class CategorysController : Controller
    {
        private readonly ICategory _ICategory;
        private readonly AppDBContext _context;

        public CategorysController(ICategory ICategory, AppDBContext context)
        {
            _ICategory = ICategory;
            _context = context;
        }

        // GET: Categories
        public async Task<IActionResult> Index()
        {
            var data = await _ICategory.GetAll();
            return View(data);
        }

        // GET: Categories/Create
        public async Task<IActionResult> Create(bool isSuccess = false, int bookId = 0)
        {
            ViewBag.IsSuccess = isSuccess;
            ViewBag.BookId = bookId;
            return View();
        }

        // POST: Categories/Create
        [HttpPost]
        public async Task<IActionResult> Create(CategoryModel categoryModel)
        {
            if (ModelState.IsValid)
            {
                int id = await _ICategory.AddToTable(categoryModel);
                if (id > 0)
                {
                    return RedirectToAction(nameof(Create), new { isSuccess = true, bookId = id });
                }
            }
            return View();
        }

        // GET: Categories/Details
        public async Task<IActionResult> Details(int id)
        {
            if (id == null)
            {
                NotFound();
            }
            var data = await _ICategory.GetById(id);
            if (data == null)
            {
                NotFound();
            }

            return View(data);
        }



        // GET: Categories/Edit
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var data = await _context.Categorys.FindAsync(id);
            if (data == null)
            {
                return NotFound();
            }
            return View(data);
        }


        [HttpPost]
        
        public  IActionResult Edit(CategoryModel CategoryModel)
        {

            if (ModelState.IsValid)
            {
                try
                {
                    _ICategory.Updated(CategoryModel);
                    
                }
                catch (DbUpdateConcurrencyException)
                {
                        return NotFound();
                }
                return RedirectToAction(nameof(Index));
            }
           
            return View(CategoryModel);
        }

        // GET: Categories/Delete
        public async Task<IActionResult> Delete(int? id, bool isSuccess = false)
        {
            ViewBag.IsSuccess = isSuccess;
            if (id == null)
            {
                return NotFound();
            }

            var data = await _context.Categorys
                .FirstOrDefaultAsync(m => m.id == id);
            if (data == null)
            {
                return NotFound();
            }

            return View(data);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var data =  _ICategory.Delete(id);
            return RedirectToAction(nameof(Index),new { isSuccess = true });
        }

        private bool CategoryExists(int id)
        {
            return _context.Categorys.Any(e => e.id == id);
        }

    }
}

DALELk/Views/Categorys/Create.cshtml
@model DALELk.Models.CategoryModel

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}




<!--This is Forms-->
<div class="col-12 grid-margin stretch-card">
    <div class="card">
        <div class="card-body">
            <h4 class="card-title">Book Table</h4>
            <p class="card-description"> Basic Book Information </p>
            <hr />
            @if (ViewBag.IsSuccess == true)
            {
                <div class="alert alert-success alert-dismissible fade show" role="alert">
                    <strong>Congratulations</strong> You have added new Category successfully. <br />
                </div>
            }

            <form method="post" enctype="multipart/form-data" class="forms-sample" asp-action="Create">

                @*data-ajax="true" data-ajax-loading="#myloader"*@

                <div asp-validation-summary="All" class="text-danger"></div>
                <div class="form-row">
                    <div class="col-md-4 mb-3">
                        <label asp-for="Cat_Name"></label>
                        <input asp-for="Cat_Name" class="form-control" placeholder="Title Book" />
                        <span asp-validation-for="Cat_Name" class="text-danger"></span>
                        <div class="valid-tooltip">
                            Looks good!
                        </div>
                    </div>
                </div>
                <div class="form-group">
                    <input type="submit" value="Create" class="btn btn-primary" />
                    <a asp-action="Index" class="btn btn-outline-dark">Back to List</a>
                </div>
            </form>
        </div>
    </div>
</div>

DALELk/Views/Categorys/Delete.cshtml
@model DALELk.Data.Category

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Cat_Name)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Cat_Name)
        </dd>
    </dl>
    <button type="button" class="btn btn-danger" data-toggle="modal" data-target="#exampleModal">
        Click Here To Delete This Item !
    </button>

</div>

<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Delete Item From Category Table</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                Are you sure you want to delete this?</
            </div>
            <div class="modal-footer">
                <form asp-action="Delete">
                    <input type="hidden" asp-for="id" />
                    <input type="submit" value="Save changes" class="btn btn-primary" />
                    <a asp-action="Index" class="btn btn-outline-dark">Back to List</a>
                </form>
            </div>
        </div>
    </div>
</div>

DALELk/Views/Categorys/Details.cshtml
@model DALELk.Models.CategoryModel

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Details</h2>

<div>

    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Cat_Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Cat_Name)
        </dd>
    </dl>
</div>
<div class="btn-group">
    <a class="btn btn-outline-success" asp-action="Edit" asp-route-id="@Model.id">Edit Item</a> 
    <a asp-action="Index" class="btn btn-outline-dark">Back to List</a>
</div>

DALELk/Views/Categorys/Edit.cshtml
@model DALELk.Data.Category

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edit Item</h2>


<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="id" />
            <div class="form-group">
                <label class="control-label">Category Name</label>
                <input asp-for="Cat_Name" class="form-control" />
                <span asp-validation-for="Cat_Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
                <a class="btn btn-light" asp-action="Index">Back to List</a>
            </div>
        </form>
    </div>
</div>



@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

DALELk/Views/Categorys/Index.cshtml
@model IEnumerable<DALELk.Models.CategoryModel>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<!--This is alert message -->


<div class="page-header">
    <div class="row">
        <div class="col-sm-12">
            <h3 class="page-title">List of Categorys</h3>
            <ul class="breadcrumb">
                <li class="breadcrumb-item"><a asp-controller="Home" asp-action="Index">Dashboard</a></li>
                @*<li class="breadcrumb-item"><a asp-controller="Home" asp-action="Index">Users</a></li>*@
                <li class="breadcrumb-item active">Category</li>
            </ul>
        </div>
    </div>
</div>


@if (ViewBag.IsSuccess == true)
{
    <div class="alert alert-success alert-dismissible fade show" role="alert">
        <strong>Wow</strong> You have deleted Category successfully.
    </div>
}

<p>
    <a asp-action="Create" class="btn btn-success">Create New</a>
</p>
<div class="row">
    <div class="col-sm-12">
        <div class="card">
            <div class="card-body">
                <div class="table-responsive">
                    <table class="datatable table table-hover table-center mb-0">
                        <thead>
                            <tr style="text-align:center">
                                <th>Category Name</th>
                                <th>Actions</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model)
                            {
                                <tr style="text-align:center">
                                    <td>

                                        @item.Cat_Name

                                    </td>
                                    <td>
                                        <a asp-controller="Categorys" asp-action="Edit" asp-route-id="@item.id" class="btn btn-outline-success">Edit</a>
                                        <a asp-controller="Categorys" asp-action="Details" asp-route-id="@item.id" class="btn btn-outline-info">Details</a>
                                        <a asp-action="Delete" asp-route-id="@item.id" class="btn btn-outline-danger">Delete</a>           
                                    </td>
                                </tr>
                            }
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>

<!-- Add Modal -->